---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: iceberg-mssql-env
  namespace: dpd-iceberg
spec:
  encryptedData:
    MYSQL_ROOT_PASSWORD: AgB+bIUPx9j0kpaSuy/8aX95DB2wxABTCY7+EeFUWvqO9plzsNRJwLGvl+4TosLnUEFjYrKh/wuosURBzs0WWhoi/NoQ5MSSEteEM6V23rt3AArBoV9PYU7SiREPkYOG/xuZE5tTQGuXNtqSEAjFBISEyAM4RSAfVB9NST5ouV/sKVXvK/otIYdHFQL5ZCLOyUyOGgiQs4KwBK9j6lqqHMTE6MT3RJUSWbtTm0pFpEk+vyEblBJZAq4vKY6htogkuBHspd/qU/anGdLB7AFX/mMunXRtVsuuqv6FusN96rYhgCp7F6mBGOaWztQL0RVLirnqCglcgX3MVI+A9w7LclR8yzd2NaPH9aMfR+oCEIfiYpShcwMji6Z15kctwTk26uUgGgwLOrPjXzYKtqdJwO4uHA2NyAlUNhKm4wJLokEuFlf7ikiXM5d2aSoRGuw+Qs4qcwM6b+ollNTmFLsIGfgNVQMu8xhhv09J35XaSlehT3+g1sMps6M+MNlF+Nqrt4YXK+OUxNEwAT85tx9fuOoPmApC18MYN91In729a5P3a6JBaCRfqkJiHgNh6msqLoR+dXmjNlmsnAWcuCQmTyj5IqCNd8f9ST3yMKiWax6OnhyPmaGVQxUFk4Vv99fRys2DnLg19snc8rtOb6XIpol+Y3HGjxDoCiN/5SbfufoVG2j9T62Am2cPz7qjULEqDpLcWpLRjDGqx8kTTt+9DImZvsA5/AmdUoD2ApZqt7XnKo++MjI/dQ9E
  template:
    metadata:
      creationTimestamp: null
      name: iceberg-mssql-env
      namespace: dpd-iceberg
